### ISSUE TITLE
Shared file systesm: Share networks

### ISSUE THREAD

**Issue by mvalkon** [gophercloud/gophercloud#130]
This issue is raised to track the development of the [`share networks`](http://developer.openstack.org/api-ref/shared-file-systems/?expanded=#share-networks) -actions in the shared file systems api v2
- [x] List share networks with details (#124)
- [x] Show share network details (#125)
- [x] Create share network (#118)
- [x] Add security service to share network
- [x] Remove security service from share network
- [x] Update share network (#126)
- [x] Delete share network (#122)

This issue is part of #114

**Comment by ehdou** [comment]
Adding and removing security services will first require to support security services

**Comment by jtopjian** [comment]
:tada:
