### ISSUE TITLE
Shared file system: Security Services

### ISSUE THREAD

**Issue by ehdou** [gophercloud/gophercloud#131]
This issue is raised to track the development of the security services in the shared file systems api v2
- [x] show security services with details (#135)
- [x] list security services with details (#134)
- [x] create a security service (#132)
- [x] delete a security service (#133)
- [x] update a security service (#136)

This issue is part of [#114](https://github.com/gophercloud/gophercloud/issues/114)

**Comment by jtopjian** [comment]
🎉
