### ISSUE TITLE
Shared file system: Share Types

### ISSUE THREAD

**Issue by ehdou** [gophercloud/gophercloud#140]
This issue is raised to track the development of the share types in the shared file systems api v2
- [x] List share types (#143)
- [x] List default share types (#144)
- [x] List extra specs for a share type (#146)
- [x] Create a share type (#141)
- [x] Show share type access with details (#149)
- [x] Set an extra spec for a share type (#147)
- [x] Unset an extra spec for a share type (#148)
- [x] Add access for a share type (#150)
- [x] Remove access for a share type (#151)
- [x] Delete a share type (#142)

This issue is part of #114

**Comment by jrperritt** [comment]
To make it easier to follow, can you put the PR next to its corresponding check box in the description like I've started doing?

**Comment by ehdou** [comment]
Of course, I'll do it now

**Comment by ehdou** [comment]
@mvalkon Can you do the same for the issues you have opened ?

**Comment by jtopjian** [comment]
🎉
