### ISSUE TITLE
volume quota api

### ISSUE THREAD

**Issue by sb10** [gophercloud/gophercloud#234]
I am doing:

    q, err := quotasets.Get(p.computeClient, os.Getenv("OS_TENANT_ID")).Extract()

and get a value like:

> &{ID:9d1c1c5a5107425e8a0c9febbfcd2152 FixedIps:-1 FloatingIps:10 InjectedFileContentBytes:10240 InjectedFilePathBytes:255 InjectedFiles:5 KeyPairs:0 MetadataItems:128 Ram:65536 SecurityGroupRules:20 SecurityGroups:10 Cores:96 Instances:64}

Using the OpenStack dashboard I can see that I have a quota on the number and total size of volumes I can create. How do I get this information via the gophercloud SDK?

(BTW, I'll note that the FloatingIps value is wrong; I'm allowed 15 and have used 2)

**Comment by jtopjian** [comment]
> How do I get this information via the gophercloud SDK?

Volume quotas are managed by the [Block Storage API](http://developer.openstack.org/api-ref/block-storage/v1/index.html#quota-sets-extension-os-quota-sets). This area isn't implemented in Gophercloud yet.

At the moment, each OpenStack project is responsible for managing its own resources' quotas. There have been several topics over the years to house them under one API.

Horizon is doing this by making calls to each OpenStack service's quota queries and aggregating them in a central dashboard. The unified `openstack` command is beginning to do the same.

> (BTW, I'll note that the FloatingIps value is wrong; I'm allowed 15 and have used 2)

That's a bit strange. Do you see a value of 15 if you do something like:

```shell
$ openstack --debug quota show <project>
$ nova --debug quota show
```

**Comment by sb10** [comment]
The openstack command doesn't work for me (just hangs), and nova quota-show gives me 10. I'll follow up with our admin here to figure that one out.

Should this issue be left open as a "feature request", or is this basically never going to happen?

**Comment by jtopjian** [comment]
> Should this issue be left open as a "feature request", or is this basically never going to happen?

I think you can leave it open. I'm sure Block Storage Quota Sets will eventually get added. I would say the goal of Gophercloud is to support all OpenStack APIs. :)

**Comment by sb10** [comment]
How about neturon quotas? I realised that my quota of 15 floating ips can be found using `neutron quota-show`. I do need to find a user's port quota which is also only listed under neutron; is that retrievable with gophercloud?

**Comment by jtopjian** [comment]
The Neutron floating IP quota  _should_ be reflected in Nova, but the functionality between the two is being removed. Maybe it already has and that's why you're seeing a different number. If that's the case, then, similar to volumes, those quotas will only be retrievable when Neutron quota support is added go Gophercloud.

**Comment by waynr** [comment]
Oh whoops, I guess I should have read the rest of the comments more closely. Sorry about that!

**Comment by waynr** [comment]
## Things I'm gonna Implement
* [ ] Get (https://github.com/gophercloud/gophercloud/pull/859)
* [ ] delete (TODO)
* [ ] Update (TODO)
* ~~Create~~ Based on the API reference documentation, it doesn't look to me
  like there is a `Create` endpoint for quotas; I guess new projects just
  inherit some OS env default

## API:
https://developer.openstack.org/api-ref/block-storage/v3/index.html#quota-sets-extension-os-quota-sets

## Schema:
I'm not showing the actual DB schema here because it makes more sense from a
request parameter validation standpoint to show the chain of calls and data
structures involved in validating a request.

Here is an example of [PUT/update request parameter validation](https://github.com/openstack/cinder/blob/master/cinder/api/contrib/quotas.py#L218-L219).

So the data structure that ultimately specifies the correct parameter names is [cinder.quotas.QUOTAS](https://github.com/openstack/cinder/blob/master/cinder/quota.py#L1234) which is a module constant initialized with [cinder.quotas.VolumeTypeQuotaEngine](https://github.com/openstack/cinder/blob/master/cinder/quota.py#L1127) which in turn:
* is a [cinder.quotas.QuotaEngine](https://github.com/openstack/cinder/blob/master/cinder/quota.py#L1127), which implements `__contains__` as
```
    def __contains__(self, resource):
        return resource in self.resources
```
* overrides `cinder.quotas.QuotaEngine.resources` and returns a dict whose keys are valid volume quota types.

So regardless of what the db schema looks like, this is the correct chain of
calls and underlying data structure that determines what keys are accepted in
the HTTP request body. The GET api uses the same data structure to retrieve a
list of quotas.

The biggest uncertainty for me is what happens if a GET call also happens to
return quotas that are specific to volume types -- it's not my intention to
implement generic support for arbitrary volume types in this feature but it's
important to ensure that nothing in the implementation of static volume quota
types breaks if they happen to be returned by the service. I believe this can
validated through acceptance testing.

## Get:
https://github.com/openstack/cinder/blob/master/cinder/api/contrib/quotas.py#L156

## Update:
https://github.com/openstack/cinder/blob/master/cinder/api/contrib/quotas.py#L193

## Delete:
https://github.com/openstack/cinder/blob/master/cinder/api/contrib/quotas.py#L337

## TODO
* [ ] Learn how to run acceptance tests against my existing openstack project.
* [ ] Write acceptance tests for new features.
* [ ] Break up https://github.com/gophercloud/gophercloud/pull/859 into three distinct PRs.

**Comment by jtopjian** [comment]
@waynr Really great write-up :)

I haven't done a deep investigation into this but, from what I understand, each volume type has a set of quota fields. For example a volume type of "foo" will have quota fields of `gigabytes_foo`, etc. Because of this, we can't have defined fields since it's impossible to account for _everyone's_ volume type names.

I think the best way to handle this is to treat these fields as "extras". This is a pattern we've implemented a few times for other areas. An example of this can be seen in the [`identity/v3/users`](https://github.com/gophercloud/gophercloud/tree/master/openstack/identity/v3/users) package. Look at how the `Extra` field is used in both the request and result structs.

You can choose a different field name if you'd like -- the name "extra" is arbitrary.

It's up to you on if you want to add support for this now or later. Getting initial support for the core fields is still a good first step :)

**Comment by waynr** [comment]
> It's up to you on if you want to add support for this now or later. Getting initial support for the core fields is still a good first step :)

I think I'll go ahead and skip this for now. I've written and run acceptance tests against one of my OS projects to verify the behavior of the code. About to open four more PRs on top of #859.
