### ISSUE TITLE
Compute v2: Flavor Extra Specs

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#540]
Flavors can contain "extra specs", or additional metadata about the flavor. Gophercloud currently does not have any support for this.

- [x] List Extra Specs (#686)
- [x] Get an Extra Spec (#686)
- [x] Create an Extra Spec (#689)
- [x] Update an Extra Spec (#712)
- [x] Delete an Extra Spec (#705)

API reference: 
* https://developer.openstack.org/api-ref/compute/#flavors-extra-specs-flavors-os-flavor-extra-specs

Nova implementation: 

* https://github.com/openstack/nova/blob/stable/pike/nova/api/openstack/compute/flavors_extraspecs.py

Schema: 

* https://github.com/openstack/nova/blob/stable/pike/nova/api/openstack/compute/schemas/flavors_extraspecs.py
* https://github.com/openstack/nova/blob/stable/pike/nova/api/validation/parameter_types.py#L333-L341

Extra Specs are defined just as Server Metadata is defined, so they will be a `map[string]string`.

**Comment by ss22ever** [comment]
@jtopjian I would like to take that.

**Comment by jtopjian** [comment]
@ss22ever You are more than welcome to, but I'd like to ask that contributors ensure the amount of work they take on at once can be completed in a timely manner.

**Comment by ss22ever** [comment]
@jtopjian Thanks, just got familiar with the project, trying my best to contribute in a timely manner.Can expect a pr soon.

**Comment by dklyle** [comment]
I haven't seen any progress on this. @ss22ever, if you are still working on this let me know. I've just done the List / Get part for now, but can finish the rest shortly.

**Comment by jtopjian** [comment]
:tada:
