### ISSUE TITLE
Discussion / New feature: Gnocchi (Metric as a Service)

### ISSUE THREAD

**Issue by ozerovandrei** [gophercloud/gophercloud#698]
**Overview**

Currently OpenStack has the [Ceilometer](https://github.com/openstack/ceilometer) Telemetry data collection service that collects event and metering data.
But all REST API functionality of that service were moved to the [Gnocchi](https://github.com/gnocchixyz/gnocchi).

I want to implement some basic functionality of the [Gnocchi API](https://gnocchi.xyz/rest.html) such as:

- Metric creating / reading / listing / deleting
- Resource creating / updating / reading / listing / deleting
- Measures pushing / batching / reading
- Archive policy reading / listing

But there is problem: Gnocchi contributors decided to move their project away from the OpenStack. You can read about reasons for that choice [here](https://julien.danjou.info/blog/2017/gnocchi-independence).
But Ceilometer project can't really save it's metrics without Gnocchi, and OpenStack operators can't get those metrics without some API. There is a note about it in the official Ceilometer [documentation](https://docs.openstack.org/ceilometer/latest/install/get_started.html):

> Ceilometer previously provided a storage and API solution. As of Newton, this functionality is officially deprecated and discouraged. For efficient storage and statistical analysis of Ceilometer data, Gnocchi is recommended.

So my question is: can I implement Gnocchi client functionality inside the Gophercloud?
If i can, should I create a new root directory inside the repository, so there will be `gnocchi` directory and `openstack` directory?
Or I should create the new directory inside `openstack`, say `openstack/metric/v1`?
Or I should start a completely new project `go-gnocchiclient` that will import Gophercloud? Because Gnocchi is not the part of OpenStack anymore (but it supports the Keystone authorization mechanism and uses similar REST API structure).

**Links**

https://github.com/gnocchixyz/gnocchi
https://gnocchi.xyz/rest.html
https://julien.danjou.info/blog/2014/openstack-ceilometer-the-gnocchi-experiment
https://julien.danjou.info/blog/2017/gnocchi-independence
https://github.com/openstack/ceilometer
https://docs.openstack.org/ceilometer/latest/install/get_started.html
(Links to code references will be provided inside merge requests)

**Status**

- [x] Gnocchi Gophercloud service client ([utils/#10](https://github.com/gophercloud/utils/pull/10))
- [x] List archive policies (+basic policy structure, [utils/#9](https://github.com/gophercloud/utils/pull/9))
- [x] Get an archive policy([utils/#14](https://github.com/gophercloud/utils/pull/14))
- [x] List resources (+basic resource structure, [utils/#12](https://github.com/gophercloud/utils/pull/12))
- [x] Get a resource ([utils/#13](https://github.com/gophercloud/utils/pull/13))
- [x] Create a resource [(utils/#16)](https://github.com/gophercloud/utils/pull/16)
- [x] Update a resource [(utils/#17)](https://github.com/gophercloud/utils/pull/17)
- [x] Delete a resource [(utils/#18)](https://github.com/gophercloud/utils/pull/18)
- [x] List metrics (+basic metric structure, [utils/#11](https://github.com/gophercloud/utils/pull/11))
- [x] Get a metric ([utils/#15](https://github.com/gophercloud/utils/pull/15))
- [x] Create a metric ([utils/#19](https://github.com/gophercloud/utils/pull/19))
- [x] Delete a metric ([utils/#20](https://github.com/gophercloud/utils/pull/20))
- [x] List measures ([utils/#21](https://github.com/gophercloud/utils/pull/21))
- [x] Push measures to a single metric ([utils/#22](https://github.com/gophercloud/utils/pull/22))
- [x] Batch measures to a different metrics via metrics IDs ([utils/#23](https://github.com/gophercloud/utils/pull/23))
- [ ] Batch measures to a different metrics via resources IDs and metric names ([utils/#24](https://github.com/gophercloud/utils/pull/24))

**Comment by jtopjian** [comment]
> So my question is: can I implement Gnocchi client functionality inside the Gophercloud?

I think this is fine. Even though Gnocchi isn't using the standard OpenStack development workflow, I'd still consider it an OpenStack-related service. Given its popularity, I think it's applicable here.

> Or I should create the new directory inside openstack, say openstack/metric/v1

I think this would be best. `metrics` plural might be better.

@jrperritt thoughts?

**Comment by jrperritt** [comment]
> thoughts?

I'm inclined to say 'no' to having this in this repo. It sounds like an OpenStack-related service insofar as it can be used with Ceilometer, but so can several other time-series databases. Maybe having it in `gophercloud/utils` would be OK.

**Comment by jtopjian** [comment]
It's certainly a blurry line. If Gnocchi used the official development workflow (gerritt et al), it would be an easy decision. The adoption and popularity of Gnocchi is what made me lean toward it being acceptable here. 

Perhaps the best deciding factor here is that the Telemetry wiki page:

https://wiki.openstack.org/wiki/Telemetry

lists Gnocchi as "non-OpenStack".

> Maybe having it in gophercloud/utils would be OK.

I think that's a fair option.

**Comment by ozerovandrei** [comment]
Thank you.
You can update assignee of that issue then.

> metrics plural might be better.

That will be a problem because I will implement package `metrics` inside Gnocchi.
This package will be used for managing Gnocchi metrics 😅 

Also official documentation suggests to create the Identity service entity for the Gnocchi with `metric` type:
https://docs.openstack.org/project-install-guide/telemetry/ocata/install-base-ubuntu.html

I think the following structure will be OK:
```
gophercloud
└── utils
    └── gnocchi
        ├── client.go
        └── v1
            └── metric
                ├── archivepolicies
                ├── measures
                ├── metrics
                └── resources
```

**Comment by jrperritt** [comment]
@ozerovandrei `gophercloud/utils` is here: https://github.com/gophercloud/utils. That's where the PRs for this should go.

**Comment by ozerovandrei** [comment]
@jrperritt oh, ok. I've moved my PR.

**Comment by jtopjian** [comment]
> oh, ok. I've moved my PR.

This is our fault - we should have been more clear about the `utils` we were talking about :smile: Thank you for moving the PR.

I apologize for possibly bike shedding, but so we don't have to do a bunch of renaming later:

I think having it under a top-level `gnocchi` directory is OK. Ideally it would be under `openstack/metric` but to differentiate it as not-an-official-openstack-service-but-will-most-likely-be-used-in-an-openstack-cloud-anyway, `gnocchi` is fine.

But instead of having a `gnocchi/v1/metric` tree, wouldn't the following work?

```
utils
└── gnocchi
    ├── client.go
    └── v1
        ├── archivepolicies
        ├── common
        ├── measures
        ├── metrics
        └── resources
```

Scanning the REST documentation, it looks like the URL structure is `v1/measure`, `v1/metric`, etc and not `v1/metric/measure`. I'm not too familiar with Gnocchi so this is a lack of knowledge on my part and please push back if this is incorrect.

Acceptance tests for Gnocchi should go under the top-level `acceptance` directory, though (`acceptance/gnocchi`).

Also, we should see if it would be possible to get integrated OpenLab testing for this. I'll ping them.

**Comment by jtopjian** [comment]
> But instead of having a gnocchi/v1/metric tree, wouldn't the following work?

From reviewing https://github.com/gophercloud/utils/pull/9/files, it looks like this is the approach which was taken, so all is good :smile:

**Comment by ozerovandrei** [comment]
@jtopjian @jrperritt thank you guys for a review on PRs.

All stuff that has been merged will allow developers to work with fundamental parts of Gnocchi - creating, updating, deleting measures, metrics and resources.
Also they will be able to read archive policies.

All additional capabilities should be implemented in separate issues in the `gophercloud/utils` repo.

You can close that issue 🎉

**Comment by jtopjian** [comment]
@ozerovandrei Thank you _very_ much for your work on this!

**Comment by jrperritt** [comment]
@ozerovandrei yes, thank you very much for your hard work on this
